/*
 * Project Name:       Phan Mem Quan Ly Tien Dien Java
 * Description:           Bai tap lon Java Quan Ly Tien Dien JDBC + Swing
 * Author:	            Nhom 18: Nam, Hao, Trung
 */
package GraphicUserInterface;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Trung
 */
public class JFrame_Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        initEvents();
    }
    
    private class MenuOptionString{
        public static final String NONE                 = "TRANG CHỦ";
        public static final String QUAN_LY_HO_TIEU_THU  = "QUẢN LÝ HỘ TIÊU THỤ";
        public static final String CAP_NHAT_CHI_SO_DIEN = "CẬP NHẬT CHỈ SỐ ĐIỆN";
        public static final String DANH_SACH_THANH_TOAN = "DANH SÁCH THANH TOÁN";
        public static final String QUAN_LY_HOA_DON      = "QUẢN LÝ HOÁ ĐƠN";
        public static final String BAO_CAO_THONG_KE     = "BÁO CÁO THỐNG KÊ";
        
        
    }
    
    private void initEvents(){
        jPanel_QLHTT.addMouseListener(new MenuOptionListener(MenuOptionString.QUAN_LY_HO_TIEU_THU, jPanel_QLHTT));
        jPanel_CNCSD.addMouseListener(new MenuOptionListener(MenuOptionString.CAP_NHAT_CHI_SO_DIEN, jPanel_CNCSD));
        jPanel_DSTT.addMouseListener(new MenuOptionListener(MenuOptionString.DANH_SACH_THANH_TOAN, jPanel_DSTT));
        jPanel_QLHD.addMouseListener(new MenuOptionListener(MenuOptionString.QUAN_LY_HOA_DON, jPanel_QLHD));
        jPanel_BCTK.addMouseListener(new MenuOptionListener(MenuOptionString.BAO_CAO_THONG_KE, jPanel_BCTK));
        
    }
    
    class MenuOptionListener implements MouseListener{
        private String menuOption = MenuOptionString.NONE;
        private JPanel jPanel = null;
        
        public MenuOptionListener(String menuOption, JPanel jPanel){
            this.menuOption = menuOption;
            this.jPanel = jPanel;
            //JOptionPane.showConfirmDialog(null, jLabel.getName());
        }
        @Override
        public void mouseClicked(MouseEvent e) {}

        @Override
        public void mousePressed(MouseEvent e) {
            changeView();
            changeColor();
        }
        
        private void changeView(){
            JPanel view = switch (menuOption){
                case MenuOptionString.NONE -> new JPanel_Home();
                case MenuOptionString.QUAN_LY_HO_TIEU_THU -> new JPanel_QuanLyHoTieuThu();
                case MenuOptionString.CAP_NHAT_CHI_SO_DIEN -> new JPanel_CapNhatChiSoDien();
                case MenuOptionString.DANH_SACH_THANH_TOAN -> new JPanel_DanhSachThanhToan();
                case MenuOptionString.QUAN_LY_HOA_DON -> new JPanel_QuanLyHoaDon();
                case MenuOptionString.BAO_CAO_THONG_KE -> new JPanel_BaoCaoThongKe();
                default -> null;
            };
            
            jPanel_Workspace.removeAll();
            jPanel_Workspace.setLayout(new BorderLayout());
            jPanel_Workspace.add(view);
            jPanel_Workspace.validate();
            jPanel_Workspace.repaint();
            
            jLabel_Title.setText(menuOption);
        }
        
        private void changeColor(){
            
            jPanel_QLHTT.setBackground(new Color(0, 153, 153));
            jPanel_CNCSD.setBackground(new Color(0, 153, 153));
            jPanel_DSTT.setBackground(new Color(0, 153, 153));
            jPanel_QLHD.setBackground(new Color(0, 153, 153));
            jPanel_BCTK.setBackground(new Color(0, 153, 153));
            
            jPanel.setBackground(new Color(96, 100, 191));
            
            //JOptionPane.showConfirmDialog(null, jLabel.getName());
        }

        @Override
        public void mouseReleased(MouseEvent e) {}

        @Override
        public void mouseEntered(MouseEvent e) {}

        @Override
        public void mouseExited(MouseEvent e) {}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Root = new javax.swing.JPanel();
        jPanel_Menu = new javax.swing.JPanel();
        jPanel_Logo = new javax.swing.JPanel();
        jLable_Logo = new javax.swing.JLabel();
        jPanel_QLHTT = new javax.swing.JPanel();
        jLabel_QLHTT = new javax.swing.JLabel();
        jPanel_CNCSD = new javax.swing.JPanel();
        jLabel_CNCSD = new javax.swing.JLabel();
        jPanel_DSTT = new javax.swing.JPanel();
        jLabel_DSTT = new javax.swing.JLabel();
        jPanel_QLHD = new javax.swing.JPanel();
        jLabel_QLHD = new javax.swing.JLabel();
        jPanel_BCTK = new javax.swing.JPanel();
        jLabel_BCTK = new javax.swing.JLabel();
        jLable_Credit = new javax.swing.JLabel();
        jPanel_View = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jPanel_Workspace = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Root.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel_Menu.setBackground(new java.awt.Color(82, 83, 81));

        jPanel_Logo.setBackground(new java.awt.Color(226, 125, 96));

        jLable_Logo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLable_Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLable_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLable_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/electricity-bill.png"))); // NOI18N
        jLable_Logo.setText("QUẢN LÝ TIỀN ĐIỆN");
        jLable_Logo.setToolTipText("");

        javax.swing.GroupLayout jPanel_LogoLayout = new javax.swing.GroupLayout(jPanel_Logo);
        jPanel_Logo.setLayout(jPanel_LogoLayout);
        jPanel_LogoLayout.setHorizontalGroup(
            jPanel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LogoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLable_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel_LogoLayout.setVerticalGroup(
            jPanel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LogoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLable_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel_QLHTT.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_QLHTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_QLHTT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_QLHTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage.png"))); // NOI18N
        jLabel_QLHTT.setText("Quản Lý Hộ Tiêu Thụ");
        jLabel_QLHTT.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_QLHTTLayout = new javax.swing.GroupLayout(jPanel_QLHTT);
        jPanel_QLHTT.setLayout(jPanel_QLHTTLayout);
        jPanel_QLHTTLayout.setHorizontalGroup(
            jPanel_QLHTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLHTTLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_QLHTT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel_QLHTTLayout.setVerticalGroup(
            jPanel_QLHTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLHTTLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_QLHTT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel_CNCSD.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_CNCSD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_CNCSD.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CNCSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        jLabel_CNCSD.setText("Cập Nhập Chỉ Số Điện");
        jLabel_CNCSD.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_CNCSDLayout = new javax.swing.GroupLayout(jPanel_CNCSD);
        jPanel_CNCSD.setLayout(jPanel_CNCSDLayout);
        jPanel_CNCSDLayout.setHorizontalGroup(
            jPanel_CNCSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CNCSDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_CNCSD, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel_CNCSDLayout.setVerticalGroup(
            jPanel_CNCSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CNCSDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_CNCSD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel_DSTT.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_DSTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_DSTT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DSTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jLabel_DSTT.setText("Danh Sách Thanh Toán");
        jLabel_DSTT.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_DSTTLayout = new javax.swing.GroupLayout(jPanel_DSTT);
        jPanel_DSTT.setLayout(jPanel_DSTTLayout);
        jPanel_DSTTLayout.setHorizontalGroup(
            jPanel_DSTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DSTTLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_DSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel_DSTTLayout.setVerticalGroup(
            jPanel_DSTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DSTTLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_DSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel_QLHD.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_QLHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_QLHD.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_QLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        jLabel_QLHD.setText("Quản Lý Hoá Đơn");
        jLabel_QLHD.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_QLHDLayout = new javax.swing.GroupLayout(jPanel_QLHD);
        jPanel_QLHD.setLayout(jPanel_QLHDLayout);
        jPanel_QLHDLayout.setHorizontalGroup(
            jPanel_QLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLHDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel_QLHDLayout.setVerticalGroup(
            jPanel_QLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QLHDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel_BCTK.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_BCTK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_BCTK.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statistic.png"))); // NOI18N
        jLabel_BCTK.setText("Báo Cáo - Thống Kê");
        jLabel_BCTK.setIconTextGap(20);

        javax.swing.GroupLayout jPanel_BCTKLayout = new javax.swing.GroupLayout(jPanel_BCTK);
        jPanel_BCTK.setLayout(jPanel_BCTKLayout);
        jPanel_BCTKLayout.setHorizontalGroup(
            jPanel_BCTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BCTKLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_BCTK, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel_BCTKLayout.setVerticalGroup(
            jPanel_BCTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BCTKLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_BCTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLable_Credit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLable_Credit.setForeground(new java.awt.Color(255, 255, 255));
        jLable_Credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLable_Credit.setText("© Nhom 18 - Java - KTPM3");

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_BCTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_QLHTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_CNCSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_DSTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_QLHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLable_Credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addComponent(jPanel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel_QLHTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel_CNCSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel_DSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel_BCTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jLable_Credit)
                .addGap(10, 10, 10))
        );

        jPanel_Title.setBackground(new java.awt.Color(0, 153, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("BÁO CÁO THỐNG KÊ");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel_WorkspaceLayout = new javax.swing.GroupLayout(jPanel_Workspace);
        jPanel_Workspace.setLayout(jPanel_WorkspaceLayout);
        jPanel_WorkspaceLayout.setHorizontalGroup(
            jPanel_WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanel_WorkspaceLayout.setVerticalGroup(
            jPanel_WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ViewLayout = new javax.swing.GroupLayout(jPanel_View);
        jPanel_View.setLayout(jPanel_ViewLayout);
        jPanel_ViewLayout.setHorizontalGroup(
            jPanel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Workspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ViewLayout.setVerticalGroup(
            jPanel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ViewLayout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Workspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_RootLayout = new javax.swing.GroupLayout(jPanel_Root);
        jPanel_Root.setLayout(jPanel_RootLayout);
        jPanel_RootLayout.setHorizontalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RootLayout.createSequentialGroup()
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_RootLayout.setVerticalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_BCTK;
    private javax.swing.JLabel jLabel_CNCSD;
    private javax.swing.JLabel jLabel_DSTT;
    private javax.swing.JLabel jLabel_QLHD;
    private javax.swing.JLabel jLabel_QLHTT;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLable_Credit;
    private javax.swing.JLabel jLable_Logo;
    private javax.swing.JPanel jPanel_BCTK;
    private javax.swing.JPanel jPanel_CNCSD;
    private javax.swing.JPanel jPanel_DSTT;
    private javax.swing.JPanel jPanel_Logo;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_QLHD;
    private javax.swing.JPanel jPanel_QLHTT;
    private javax.swing.JPanel jPanel_Root;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JPanel jPanel_View;
    private javax.swing.JPanel jPanel_Workspace;
    // End of variables declaration//GEN-END:variables
}
