/*
 * Project Name:       Phan Mem Quan Ly Tien Dien Java
 * Description:           Bai tap lon Java Quan Ly Tien Dien JDBC + Swing
 * Author:	            Nhom 18: Nam, Hao, Trung
 */
package GraphicUserInterface;

import BusinessLogicLayer.QuanLyHoTieuThu_BLL;
import Objects.KhachHang;
import Utility.JCustomTable;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Admin
 */
public class JPanel_QuanLyHoTieuThu extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_QuanLyHoTieuThu
     */
    public JPanel_QuanLyHoTieuThu() {
        initComponents();
        initjTable_HoTieuThu();
        initEvents();
    }
    
    QuanLyHoTieuThu_BLL quanLyHoTieuThuBLL = new QuanLyHoTieuThu_BLL();
    JCustomTable jCustomTable_HoTieuThu;
    
    private void initjTable_HoTieuThu(){
        jCustomTable_HoTieuThu = new JCustomTable.JCustomTableBuilder()
                .addColumnName("Mã khách hàng")
                .addColumnName("Họ tên")
                .addColumnName("Địa chỉ")
                .addColumnName("CCCD")
                .addColumnName("Ngày sinh")
                .addColumnName("Số điện thoại")
                .setTable(jTable_HoTieuThu)
                .setScrollPane(jScrollPane_QuanLyHoTieuDung)
                .build();
        
        jCustomTable_HoTieuThu.clear();
        jCustomTable_HoTieuThu.addRows(quanLyHoTieuThuBLL.getListObject());
    }
    
    void initEvents(){
        jTextField_TimKiem.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent e) {
                jCustomTable_HoTieuThu.setRowFilter(jTextField_TimKiem.getText());
            }
            public void keyReleased(KeyEvent e) {
                jCustomTable_HoTieuThu.setRowFilter(jTextField_TimKiem.getText());
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Root = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TimKiem = new javax.swing.JTextField();
        jScrollPane_QuanLyHoTieuDung = new javax.swing.JScrollPane();
        jTable_HoTieuThu = new javax.swing.JTable();
        jPanel_Them = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Them2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel_Root.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Tìm kiếm");

        jTextField_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jScrollPane_QuanLyHoTieuDung.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTable_HoTieuThu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable_HoTieuThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Địa chỉ", "CCCD", "Ngày sinh", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_HoTieuThu.setRowHeight(20);
        jTable_HoTieuThu.setShowGrid(false);
        jScrollPane_QuanLyHoTieuDung.setViewportView(jTable_HoTieuThu);

        jPanel_Them.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel1.setText("Thêm");

        javax.swing.GroupLayout jPanel_ThemLayout = new javax.swing.GroupLayout(jPanel_Them);
        jPanel_Them.setLayout(jPanel_ThemLayout);
        jPanel_ThemLayout.setHorizontalGroup(
            jPanel_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        jPanel_ThemLayout.setVerticalGroup(
            jPanel_ThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel_Them2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jLabel4.setText("Sửa");

        javax.swing.GroupLayout jPanel_Them2Layout = new javax.swing.GroupLayout(jPanel_Them2);
        jPanel_Them2.setLayout(jPanel_Them2Layout);
        jPanel_Them2Layout.setHorizontalGroup(
            jPanel_Them2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        jPanel_Them2Layout.setVerticalGroup(
            jPanel_Them2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_RootLayout = new javax.swing.GroupLayout(jPanel_Root);
        jPanel_Root.setLayout(jPanel_RootLayout);
        jPanel_RootLayout.setHorizontalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RootLayout.createSequentialGroup()
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_QuanLyHoTieuDung, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(jPanel_RootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_RootLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jPanel_Them2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_RootLayout.setVerticalGroup(
            jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_QuanLyHoTieuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Them2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_Root;
    private javax.swing.JPanel jPanel_Them;
    private javax.swing.JPanel jPanel_Them1;
    private javax.swing.JPanel jPanel_Them2;
    private javax.swing.JScrollPane jScrollPane_QuanLyHoTieuDung;
    private javax.swing.JTable jTable_HoTieuThu;
    private javax.swing.JTextField jTextField_TimKiem;
    // End of variables declaration//GEN-END:variables
}
